### ISSUE TITLE
Crashing app issue on simulator & Device

### ISSUE THREAD

**Issue by arvindsen14** [kayako/KayakoMessengeriOS#14] opened 2017-10-18 09:18 UTC
Dear Kayako Team ,

Below are the two issue I am getting.
1. Close button image is not visible, due to that hard to dismiss chat window.
![simulator screen shot - iphone 7 plus - 2017-10-18 at 14 41 18](https://user-images.githubusercontent.com/9761828/31710619-2aa95878-b413-11e7-8447-e363ace22583.png)

2. When tapping on send message button on chat window app getting crash.
Here is the debug code.

Assertion failure in -[ASNetworkImageNode layer], /Personal-Things/Projects/OtherApp/ClassMonitor/AppCode/ClassMonitor_V1/Pods/Texture/Source/ASDisplayNode.mm:710
2017-10-18 14:43:15.125969+0530 ClassMonitor[8896:294258] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This method must be called on the main thread'

![screen shot 2017-10-18 at 3 04 34 pm](https://user-images.githubusercontent.com/9761828/31711437-c02f00e4-b415-11e7-92c0-0d9dd1844af8.png)

![screen shot 2017-10-18 at 4 48 20 pm](https://user-images.githubusercontent.com/9761828/31716187-4e07e08a-b424-11e7-9395-6a7e294f1d70.png)

Please do needful here.

Best,
Arvind

**Comment by codeOfRobin** [comment] 2017-10-18 09:29
> Close button image is not visible, due to that hard to dismiss chat window.

Looks like #3 has resurfaced 🤔. We'll look into this along with #10 


As for the crash, I wasn't able to reproduce the crash on my instance. Could you send me a screenshot of your stacktrace? It'll look like this (I simulated a crash using a `fatalerror()`:

![screen shot 2017-10-18 at 2 59 17 pm](https://user-images.githubusercontent.com/5009041/31711186-fa96e19e-b414-11e7-8677-5a915b5d2be8.png)

**Comment by arvindsen14** [comment] 2017-10-18 11:20
Here is the stack image.

![screen shot 2017-10-18 at 4 48 20 pm](https://user-images.githubusercontent.com/9761828/31716205-646e1772-b424-11e7-95ae-c698c0c5676d.png)

**Comment by codeOfRobin** [comment] 2017-10-31 11:48
Hey Arvind!

Thank you for your patience. I’m back from vacation, and your issue should be fixed soon. I’ll post another comment here when the latest pod is out 😁

**Comment by arvindsen14** [comment] 2017-10-31 18:13
Ok...& thanks to update.

**Comment by codeOfRobin** [comment] 2017-11-07 05:23
Hey! Could you try out the new pod version 0.3.0? Should fix some issues you've been experiencing

**Comment by arvindsen14** [comment] 2017-11-07 05:39
Not yet tried but will soon try new pod version 0.3.0 and will let you know
result...Thanks again to reply.

**Comment by arvindsen14** [comment] 2017-11-09 06:02
Ok...& thanks to update

**Comment by codeOfRobin** [comment] 2017-11-09 06:05
I hope this means it worked for you @arvindsen14 😄

**Comment by arvindsen14** [comment] 2017-11-09 09:40
Thanks Robin,

New pod version install successfully.
But when I tried to run the code on device app getting crash...
And the reason is


Assertion failure in -[ASTextKitComponents dealloc],
/Personal-Things/Projects/OtherApp/ClassMonitor/AppCode/ClassMonitor_V1/Pods/Texture/Source/TextKit/ASTextKitComponents.mm:68


Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: 'This method must be called on
the main thread'
*** First throw call stack:

[image: Inline image 1]

Please do needful.
Why its not working.

Thanks,
Arvind

**Comment by codeOfRobin** [comment] 2017-11-09 10:42
Ah, looks like it's a bug in texture that we're running into. https://github.com/TextureGroup/Texture/pull/610

Apparently they've updated in their master branch, I think switching to it will fix the issue.

**Comment by codeOfRobin** [comment] 2017-11-09 10:49
In case you're in a bit of a hurry and need to make a release urgently, I'd suggest installing Messenger using [Carthage](https://github.com/carthage/carthage/) (That's what we use here at Kayako and it's been working flawlessly for us). Refer to our docs here: https://developer.kayako.com/messenger/ios/installation/

**Comment by codeOfRobin** [comment] 2017-11-14 08:51
Closing due to inactivity.

**Closed by codeOfRobin** 2017-11-14 08:51 UTC
Labels: help wanted
