### ISSUE TITLE
Crash: Nodes with a .layoutSpecBlock must not also implement -layoutSpecThatFits:

### ISSUE THREAD

**Issue by chili-ios** [kayako/KayakoMessengeriOS#9] opened 2017-10-03 07:38 UTC
Hi,

I'm trying to implement your SKD but have a crash when tapping `start a new conversation`.
```
2017-10-03 10:37:31.050114+0300 Forex4you[98948:39678943] *** Assertion failure in -[ASButtonNode setLayoutSpecBlock:], /Users/igorsnemenonoks/Documents/workspace/Trade7ios/Pods/Texture/Source/ASDisplayNode+Layout.mm:148
2017-10-03 10:37:31.064567+0300 Forex4you[98948:39678943] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Nodes with a .layoutSpecBlock must not also implement -layoutSpecThatFits:'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001145d21cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000113f34f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001145d7362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001139d9089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   AsyncDisplayKit                     0x000000010dd66d2e -[ASDisplayNode(ASLayout) setLayoutSpecBlock:] + 318
	5   KayakoMessenger                     0x000000010f0d4de5 _T015KayakoMessenger14ALTextInputBarC10commonInit33_ECC1FF127ED6D0A40C1B66A1F6AAD320LLyyF + 7061
	6   KayakoMessenger                     0x000000010f0d2705 _T015KayakoMessenger14ALTextInputBarCACSC6CGRectV5frame_tcfc + 2661
	7   KayakoMessenger                     0x000000010f0d2746 _T015KayakoMessenger14ALTextInputBarCACSC6CGRectV5frame_tcfcTo + 38
	8   UIKit                               0x0000000111621f66 -[UIView init] + 62
	9   KayakoMessenger                     0x000000010f0db423 _T0So6UIViewCABycfcTO + 19
	10  KayakoMessenger                     0x000000010f0d60dc _T0So6UIViewCABycfC + 60
	11  KayakoMessenger                     0x000000010f2314d1 _T015KayakoMessenger22MessagesViewControllerCAcA17ConversationStateO012conversationG0_AA13ConfigurationV13configurationAA11StarterDataV07starterL0AA6ClientC6clienttcfc + 2033
	12  KayakoMessenger                     0x000000010f230c84 _T015KayakoMessenger22MessagesViewControllerCAcA17ConversationStateO012conversationG0_AA13ConfigurationV13configurationAA11StarterDataV07starterL0AA6ClientC6clienttcfC + 2004
	13  KayakoMessenger                     0x000000010f189446 _T015KayakoMessenger24HomeScreenViewControllerC27newConversationButtonTappedyyF + 1814
	14  KayakoMessenger                     0x000000010f1895e4 _T015KayakoMessenger24HomeScreenViewControllerC27newConversationButtonTappedyyFTo + 36
	15  AsyncDisplayKit                     0x000000010dd4ab8c -[ASControlNode sendActionsForControlEvents:withEvent:] + 1820
	16  KayakoMessenger                     0x000000010f2529dd _T015KayakoMessenger21NewConversationButtonC12touchesEndedys3SetVySo7UITouchCG_So7UIEventCSg4withtF + 1357
	17  KayakoMessenger                     0x000000010f252d98 _T015KayakoMessenger21NewConversationButtonC12touchesEndedys3SetVySo7UITouchCG_So7UIEventCSg4withtFTo + 104
	18  AsyncDisplayKit                     0x000000010dcc0cd2 -[_ASDisplayView touchesEnded:withEvent:] + 162
	19  UIKit                               0x00000001115fcd4f -[UIWindow _sendTouchesForEvent:] + 2807
	20  UIKit                               0x00000001115fe472 -[UIWindow sendEvent:] + 4124
	21  UIKit                               0x00000001115a3802 -[UIApplication sendEvent:] + 352
	22  UIKit                               0x0000000111ed5a50 __dispatchPreprocessedEventFromEventQueue + 2809
	23  UIKit                               0x0000000111ed85b7 __handleEventQueueInternal + 5957
	24  CoreFoundation                      0x00000001145752b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x0000000114614d31 __CFRunLoopDoSource0 + 81
	26  CoreFoundation                      0x0000000114559c19 __CFRunLoopDoSources0 + 185
	27  CoreFoundation                      0x00000001145591ff __CFRunLoopRun + 1279
	28  CoreFoundation                      0x0000000114558a89 CFRunLoopRunSpecific + 409
	29  GraphicsServices                    0x00000001196169c6 GSEventRunModal + 62
	30  UIKit                               0x0000000111586d30 UIApplicationMain + 159
	31  Forex4you                           0x000000010c95ee9f main + 111
	32  libdyld.dylib                       0x00000001163d9d81 start + 1
	33  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by codeOfRobin** [comment] 2017-10-03 07:43
Hey! This looks like a dupe of #8 🤔  . I'll look into the issue as soon as I can (thanks for raising this issue by the way!)

**Comment by codeOfRobin** [comment] 2017-10-08 10:19
Hey! I think I've fixed the issue with #5 . Could you pull the latest pod (v0.2.2) or `carthage update` ?

**Comment by chili-ios** [comment] 2017-10-16 09:03
yep, it's fixed now. 

Now I have another bug -> 
![image](https://user-images.githubusercontent.com/19732707/31603817-06bc774c-b26a-11e7-8de4-d5f7489783d9.png)

**Comment by codeOfRobin** [comment] 2017-10-16 09:12
Interesting. This looks like it's separate, so I'm going to close this issue and create a new one.

**Closed by codeOfRobin** 2017-10-16 09:12 UTC

**Comment by codeOfRobin** [comment] 2017-10-16 09:14
PS, could you post any replies in #11 ? That'd be great, thank you 😄
