### ISSUE TITLE
Tapping on Start a new conversation button app getting crash

### ISSUE THREAD

**Issue by arvindsen14** [kayako/KayakoMessengeriOS#12] opened 2017-10-17 09:38 UTC
Hello Team,

I have been implemented Kayako messenger in my app swift (ios 11.0), but when I am tapping on start a new conversation button, my app is getting crash, due to a run time error. Below is that.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Nodes with a .layoutSpecBlock must not also implement -layoutSpecThatFits:'

Can you please do needful and help me out how I can overcome with this issue.

Thanks,
Arvind

**Comment by codeOfRobin** [comment] 2017-10-17 09:40
Hey Arvind!

The issue is fixed in 0.2.3 (we're a little behind on updating our docs, will post an update soon)
You can get the latest version by adding a version at the end of your pod, like so
```
pod 'KayakoMessenger', '~> 0.2.3'
```
Or just run `carthage update` with the master branch

**Comment by arvindsen14** [comment] 2017-10-17 10:09
Thanks Robin for your quick response.
I will try this and let you update.
Thanks again

Best,
Arvind

**Comment by arvindsen14** [comment] 2017-10-18 06:56
Dear Robin,

That issue I had mentioned on portal is fixed but when I have been starting
chatting and tapping on send button application again crashing.
Please do needful for that.

Best,
Arvind

**Comment by arvindsen14** [comment] 2017-10-18 06:57
Here is the debug error.

Assertion failure in -[ASNetworkImageNode layer],
/Personal-Things/Projects/OtherApp/ClassMonitor/AppCode/ClassMonitor_V1/Pods/Texture/Source/ASDisplayNode.mm:710
2017-10-18 12:08:37.499794+0530 ClassMonitor[7180:233586] *** Terminating
app due to uncaught exception 'NSInternalInconsistencyException', reason:
'This method must be called on the main thread'

**Comment by codeOfRobin** [comment] 2017-10-18 07:28
Hey Arvind!

> That issue I had mentioned on portal is fixed

Great! 

> application again crashing.
> Assertion failure in -[ASNetworkImageNode layer],

Could you open up a new issue for this? It'd be easier to refer to in case someone else also has it. Meanwhile, I'm going to close this one.

**Closed by codeOfRobin** 2017-10-18 07:28 UTC
